version: "3.7"

services:
  frontend:
    container_name: frontend-starter
    build:
      dockerfile: frontend.docker
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
